# Generated by Django 4.2.16 on 2024-09-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_receipt_number_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(max_length=255),
        ),
    ]
