# Generated by Django 4.2.16 on 2024-09-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_alter_trader_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='number_of_posts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
