# Generated by Django 4.2.16 on 2024-09-07 13:09

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),  # Ensure this matches the migration file for the Trader model
    ]

    operations = [
        migrations.CreateModel(
            name='TextileBale',
            fields=[
                ('bale_id', models.AutoField(primary_key=True, serialize=False)),
                ('trader', models.ForeignKey(on_delete=models.CASCADE, to='traders.Trader')),
                ('waste_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
