# Generated by Django 4.2.16 on 2024-09-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textilebale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textilebale',
            name='waste_type',
            field=models.CharField(max_length=255),
        ),
    ]
