# Generated by Django 4.2.16 on 2024-09-11 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traders', '0001_initial'),
        ('textilebale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textilebale',
            options={'permissions': [('post_textilebale_custom', 'Can post textile bale'), ('view_textilebale_custom', 'Can view textile bale')]},
        ),
        migrations.RemoveField(
            model_name='textilebale',
            name='location',
        ),
        migrations.AddField(
            model_name='textilebale',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='textile_bales_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textilebale',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textile_bales', to='traders.trader'),
        ),
    ]
