# Generated by Django 4.2.16 on 2024-09-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textilebale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootAgent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('foot_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='footagent.footagent')),
                ('textile_bale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='textilebale.textilebale')),
            ],
        ),
    ]
