# Generated by Django 4.2.16 on 2024-09-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('recycler', 'Recycler'), ('public', 'Public User')], max_length=50)),
            ],
        ),
    ]
