# Generated by Django 4.2.16 on 2024-09-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextileBale',
            fields=[
                ('bale_id', models.AutoField(primary_key=True, serialize=False)),
                ('waste_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader')),
            ],
        ),
    ]
