# Generated by Django 4.2.16 on 2024-09-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textilebale', '0002_alter_textilebale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textilebale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='textile_bales/'),
        ),
    ]
