# Generated by Django 4.2.16 on 2024-09-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textilebale', '0003_textilebale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textilebale',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textile_bales', to=settings.AUTH_USER_MODEL),
        ),
    ]
