# Generated by Django 4.2.16 on 2024-09-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('material', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traders.trader')),
            ],
        ),
    ]
