# Generated by Django 4.2.16 on 2024-09-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock_quantity',
        ),
    ]
